[build]
  command = "bash build-netlify.sh"
  publish = "build"

[build.environment]
  NODE_VERSION = "20"
  RUST_VERSION = "1.75.0"

[[headers]]
  for = "/*"
  [headers.values]
    X-Content-Type-Options = "nosniff"
    X-Frame-Options = "DENY"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'wasm-unsafe-eval' https://www.googletagmanager.com https://www.google-analytics.com; style-src 'self' 'unsafe-inline'; img-src 'self' data: https://www.google-analytics.com https://www.googletagmanager.com https://*.amazonaws.com https://*.tile.opentopomap.org https://*.opentopography.org https://*.maptiler.com; connect-src 'self' blob: https://www.google-analytics.com https://analytics.google.com https://www.googletagmanager.com https://api.iconify.design https://api.unisvg.com https://api.simplesvg.com https://*.opentopography.org https://*.maptiler.com;  worker-src 'self' blob:; child-src 'self' blob:; form-action 'self'; frame-ancestors 'none';"